/*
 * Copyright (c) 2023 ADN's. All right reserved.
 */

const Text_color = {
    "w": "white",
    "s": "silver",
    "u": "black",
    "r": "red",
    "o": "orange",
    "y": "yellow",
    "g": "green",
    "c": "cyan",
    "b": "blue",
    "m": "darkgray",
    "HUD_COLOUR_PURE_WHITE" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_WHITE" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_BLACK" : "rgba(0, 0, 0, 255)",
    "HUD_COLOUR_GREY" : "rgba(127, 127, 127, 255)",
    "HUD_COLOUR_GREYLIGHT" : "rgba(190, 190, 190, 255)",
    "HUD_COLOUR_GREYDARK" : "rgba(64, 64, 64, 255)",
    "HUD_COLOUR_RED" : "rgba(255, 0, 0, 255)",
    "HUD_COLOUR_REDLIGHT" : "rgba(255, 102, 102, 255)",
    "HUD_COLOUR_REDDARK" : "rgba(153, 0, 0, 255)",
    "HUD_COLOUR_BLUE" : "rgba(0, 0, 255, 255)",
    "HUD_COLOUR_BLUELIGHT" : "rgba(102, 102, 255, 255)",
    "HUD_COLOUR_BLUEDARK" : "rgba(0, 0, 153, 255)",
    "HUD_COLOUR_YELLOW" : "rgba(255, 255, 0, 255)",
    "HUD_COLOUR_YELLOWLIGHT" : "rgba(255, 255, 102, 255)",
    "HUD_COLOUR_YELLOWDARK" : "rgba(153, 153, 0, 255)",
    "HUD_COLOUR_ORANGE" : "rgba(255, 128, 0, 255)",
    "HUD_COLOUR_ORANGELIGHT" : "rgba(255, 178, 102, 255)",
    "HUD_COLOUR_ORANGEDARK" : "rgba(153, 76, 0, 255)",
    "HUD_COLOUR_GREEN" : "rgba(0, 255, 0, 255)",
    "HUD_COLOUR_GREENLIGHT" : "rgba(102, 255, 102, 255)",
    "HUD_COLOUR_GREENDARK" : "rgba(0, 153, 0, 255)",
    "HUD_COLOUR_PURPLE" : "rgba(153, 0, 153, 255)",
    "HUD_COLOUR_PURPLELIGHT" : "rgba(204, 102, 255, 255)",
    "HUD_COLOUR_PURPLEDARK" : "rgba(102, 0, 102, 255)",
    "HUD_COLOUR_PINK" : "rgba(255, 0, 255, 255)",
    "HUD_COLOUR_RADAR_HEALTH" : "rgba(114, 204, 114, 255)",
    "HUD_COLOUR_RADAR_ARMOUR" : "rgba(159, 159, 255, 255)",
    "HUD_COLOUR_RADAR_DAMAGE" : "rgba(214, 93, 14, 255)",
    "HUD_COLOUR_NET_PLAYER1" : "rgba(159, 212, 104, 255)",
    "HUD_COLOUR_NET_PLAYER2" : "rgba(159, 159, 255, 255)",
    "HUD_COLOUR_NET_PLAYER3" : "rgba(255, 212, 104, 255)",
    "HUD_COLOUR_NET_PLAYER4" : "rgba(255, 159, 104, 255)",
    "HUD_COLOUR_NET_PLAYER5" : "rgba(255, 104, 159, 255)",
    "HUD_COLOUR_NET_PLAYER6" : "rgba(212, 104, 159, 255)",
    "HUD_COLOUR_NET_PLAYER7" : "rgba(159, 104, 212, 255)",
    "HUD_COLOUR_NET_PLAYER8" : "rgba(104, 159, 212, 255)",
    "HUD_COLOUR_NET_PLAYER9" : "rgba(104, 212, 159, 255)",
    "HUD_COLOUR_NET_PLAYER10" : "rgba(212, 159, 104, 255)",
    "HUD_COLOUR_NET_PLAYER11" : "rgba(212, 104, 104, 255)",
    "HUD_COLOUR_NET_PLAYER12" : "rgba(104, 212, 104, 255)",
    "HUD_COLOUR_NET_PLAYER13" : "rgba(104, 104, 212, 255)",
    "HUD_COLOUR_NET_PLAYER14" : "rgba(159, 212, 159, 255)",
    "HUD_COLOUR_NET_PLAYER15" : "rgba(159, 159, 212, 255)",
    "HUD_COLOUR_NET_PLAYER16" : "rgba(212, 159, 159, 255)",
    "HUD_COLOUR_NET_PLAYER17" : "rgba(212, 212, 104, 255)",
    "HUD_COLOUR_NET_PLAYER18" : "rgba(212, 104, 212, 255)",
    "HUD_COLOUR_NET_PLAYER19" : "rgba(104, 212, 212, 255)",
    "HUD_COLOUR_NET_PLAYER20" : "rgba(159, 104, 104, 255)",
    "HUD_COLOUR_NET_PLAYER21" : "rgba(104, 159, 104, 255)",
    "HUD_COLOUR_NET_PLAYER22" : "rgba(104, 104, 159, 255)",
    "HUD_COLOUR_NET_PLAYER23" : "rgba(206, 169, 13, 255)",
    "HUD_COLOUR_NET_PLAYER24" :	"rgba(71, 99, 173, 255)",
    "HUD_COLOUR_NET_PLAYER25" :	"rgba(42, 166, 185, 255)",
    "HUD_COLOUR_NET_PLAYER26" :	"rgba(186, 157, 125, 255)",
    "HUD_COLOUR_NET_PLAYER27" :	"rgba(201, 225, 255, 255)",
    "HUD_COLOUR_NET_PLAYER28" :	"rgba(240, 240, 150, 255)",
    "HUD_COLOUR_NET_PLAYER29" :	"rgba(237, 140, 161, 255)",
    "HUD_COLOUR_NET_PLAYER30" :	"rgba(249, 138, 138, 255)",
    "HUD_COLOUR_NET_PLAYER31" :	"rgba(252, 239, 166, 255)",
    "HUD_COLOUR_NET_PLAYER32" :	"rgba(240, 240, 240, 255)",
    "HUD_COLOUR_SIMPLEBLIP_DEFAULT" : "rgba(159, 201, 166, 255)",
    "HUD_COLOUR_MENU_BLUE" : "rgba(140, 140, 140, 255)",
    "HUD_COLOUR_MENU_BLUE_EXTRA_DARK" : "rgba(40, 40, 40, 255)",
    "HUD_COLOUR_MENU_YELLOW" : "rgba(240, 160, 0, 255)",
    "HUD_COLOUR_MENU_GREY" : "rgba(140, 140, 140, 255)",
    "HUD_COLOUR_MENU_GREY_DARK" : "rgba(60, 60, 60, 255)",
    "HUD_COLOUR_MENU_HIGHLIGHT" : "rgba(30, 30, 30, 255)",
    "HUD_COLOUR_MENU_STANDARD" : "rgba(140, 140, 140, 255)",
    "HUD_COLOUR_MENU_DIMMED" : "rgba(75, 75, 75, 255)",
    "HUD_COLOUR_MENU_EXTRA_DIMMED" : "rgba(50, 50, 50, 255)",
    "HUD_COLOUR_BRIEF_TITLE" : "rgba(95, 95, 95, 255)",
    "HUD_COLOUR_MID_GREY_MP" : "rgba(100, 100, 100, 255)",
    "HUD_COLOUR_NET_PLAYER1_DARK" : "rgba(93, 39, 39, 255)",
    "HUD_COLOUR_NET_PLAYER2_DARK" : "rgba(77, 55, 89, 255)",
    "HUD_COLOUR_NET_PLAYER3_DARK" : "rgba(124, 62, 99, 255)",
    "HUD_COLOUR_NET_PLAYER4_DARK" : "rgba(120, 80, 80, 255)",
    "HUD_COLOUR_NET_PLAYER5_DARK" : "rgba(87, 72, 66, 255)",
    "HUD_COLOUR_NET_PLAYER6_DARK" : "rgba(74, 103, 83, 255)",
    "HUD_COLOUR_NET_PLAYER7_DARK" : "rgba(60, 85, 88, 255)",
    "HUD_COLOUR_NET_PLAYER8_DARK" : "rgba(105, 105, 64, 255)",
    "HUD_COLOUR_NET_PLAYER9_DARK" : "rgba(72, 63, 76, 255)",
    "HUD_COLOUR_NET_PLAYER10_DARK" : "rgba(53, 98, 95, 255)",
    "HUD_COLOUR_NET_PLAYER11_DARK" : "rgba(107, 98, 76, 255)",
    "HUD_COLOUR_NET_PLAYER12_DARK" : "rgba(117, 71, 40, 255)",
    "HUD_COLOUR_NET_PLAYER13_DARK" : "rgba(76, 101, 117, 255)",
    "HUD_COLOUR_NET_PLAYER14_DARK" : "rgba(65, 35, 47, 255)",
    "HUD_COLOUR_NET_PLAYER15_DARK" : "rgba(72, 71, 61, 255)",
    "HUD_COLOUR_NET_PLAYER16_DARK" : "rgba(85, 58, 47, 255)",
    "HUD_COLOUR_NET_PLAYER17_DARK" : "rgba(87, 84, 84, 255)",
    "HUD_COLOUR_NET_PLAYER18_DARK" : "rgba(116, 71, 77, 255)",
    "HUD_COLOUR_NET_PLAYER19_DARK" : "rgba(93, 107, 45, 255)",
    "HUD_COLOUR_NET_PLAYER20_DARK" : "rgba(6, 61, 43, 255)",
    "HUD_COLOUR_NET_PLAYER21_DARK" : "rgba(61, 98, 127, 255)",
    "HUD_COLOUR_NET_PLAYER22_DARK" : "rgba(85, 30, 115, 255)",
    "HUD_COLOUR_NET_PLAYER23_DARK" : "rgba(103, 84, 6, 255)",
    "HUD_COLOUR_NET_PLAYER24_DARK" : "rgba(35, 49, 86, 255)",
    "HUD_COLOUR_NET_PLAYER25_DARK" : "rgba(21, 83, 92, 255)",
    "HUD_COLOUR_NET_PLAYER26_DARK" : "rgba(93, 98, 62, 255)",
    "HUD_COLOUR_NET_PLAYER27_DARK" : "rgba(100, 112, 127, 255)",
    "HUD_COLOUR_NET_PLAYER28_DARK" : "rgba(120, 120, 75, 255)",
    "HUD_COLOUR_NET_PLAYER29_DARK" : "rgba(152, 76, 93, 255)",
    "HUD_COLOUR_NET_PLAYER30_DARK" : "rgba(124, 69, 69, 255)",
    "HUD_COLOUR_NET_PLAYER31_DARK" : "rgba(10, 43, 50, 255)",
    "HUD_COLOUR_NET_PLAYER32_DARK" : "rgba(95, 95, 10, 255)",
    "HUD_COLOUR_BRONZE" : "rgba(180, 130, 97, 255)",
    "HUD_COLOUR_SILVER" : "rgba(150, 153, 161, 255)",
    "HUD_COLOUR_GOLD" : "rgba(214, 181, 99, 255)",
    "HUD_COLOUR_PLATINUM" : "rgba(166, 221, 190, 255)",
    "HUD_COLOUR_GANG1" : "rgba(29, 100, 153, 255)",
    "HUD_COLOUR_GANG2" : "rgba(214, 116, 15, 255)",
    "HUD_COLOUR_GANG3" : "rgba(135, 125, 142, 255)",
    "HUD_COLOUR_GANG4" : "rgba(229, 119, 185, 255)",
    "HUD_COLOUR_SAME_CREW" : "rgba(252, 239, 166, 255)",
    "HUD_COLOUR_FREEMODE" : "rgba(45, 110, 185, 255)",
    "HUD_COLOUR_PAUSE_BG" : "rgba(0, 0, 0, 186)",
    "HUD_COLOUR_FRIENDLY" : "rgba(93, 182, 229, 255)",
    "HUD_COLOUR_ENEMY" : "rgba(194, 80, 80, 255)",
    "HUD_COLOUR_FREEMODE_DARK" : "rgba(22, 55, 92, 255)",
    "HUD_COLOUR_INACTIVE_MISSION" : "rgba(154, 154, 154, 255)",
    "HUD_COLOUR_DAMAGE" : "rgba(194, 80, 80, 255)",
    "HUD_COLOUR_PINKLIGHT" : "rgba(252, 115, 201, 255)",
    "HUD_COLOUR_PM_MITEM_HIGHLIGHT" : "rgba(252, 177, 49, 255)",
    "HUD_COLOUR_SCRIPT_VARIABLE" : "rgba(0, 0, 0, 255)",
    "HUD_COLOUR_YOGA" : "rgba(109, 247, 204, 255)",
    "HUD_COLOUR_TENNIS" : "rgba(241, 101, 34, 255)",
    "HUD_COLOUR_GOLF" : "rgba(214, 189, 97, 255)",
    "HUD_COLOUR_SOCIAL_CLUB" : "rgba(234, 153, 28, 255)",
    "HUD_COLOUR_PLATFORM_BLUE" : "rgba(11, 55, 123, 255)",
    "HUD_COLOUR_PLATFORM_GREEN" : "rgba(146, 200, 62, 255)",
    "HUD_COLOUR_PLATFORM_GREY" : "rgba(234, 153, 28, 255)",
    "HUD_COLOUR_FACEBOOK_BLUE" : "rgba(66, 89, 148, 255)",
    "HUD_COLOUR_INGAME_BG" : "rgba(0, 0, 0, 186)",
    "HUD_COLOUR_WAYPOINT" : "rgba(164, 76, 242, 255)",
    "HUD_COLOUR_MICHAEL" : "rgba(101, 180, 212, 255)",
    "HUD_COLOUR_FRANKLIN" : "rgba(171, 237, 171, 255)",
    "HUD_COLOUR_TREVOR" : "rgba(255, 163, 87, 255)",
    "HUD_COLOUR_GOLF_P2" : "rgba(235, 239, 30, 255)",
    "HUD_COLOUR_GOLF_P3" : "rgba(255, 149, 14, 255)",
    "HUD_COLOUR_GOLF_P4" : "rgba(246, 60, 161, 255)",
    "HUD_COLOUR_WAYPOINTLIGHT" : "rgba(210, 166, 249, 255)",
    "HUD_COLOUR_WAYPOINTDARK" : "rgba(82, 38, 121, 255)",
    "HUD_COLOUR_PANEL_LIGHT" : "rgba(0, 0, 0, 77)",
    "HUD_COLOUR_MICHAEL_DARK" : "rgba(72, 103, 116, 255)",
    "HUD_COLOUR_FRANKLIN_DARK" : "rgba(85, 118, 85, 255)",
    "HUD_COLOUR_TREVOR_DARK" : "rgba(127, 81, 43, 255)",
    "HUD_COLOUR_PAUSEMAP_TINT" : "rgba(0, 0, 0, 215)",
    "HUD_COLOUR_PAUSE_DESELECT" : "rgba(100, 100, 100, 127)",
    "HUD_COLOUR_PM_WEAPONS_LOCKED" : "rgba(240, 240, 240, 191)",
    "HUD_COLOUR_PAUSEMAP_TINT_HALF" : "rgba(0, 0, 0, 215)",
    "HUD_COLOUR_NORTH_BLUE_OFFICIAL" : "rgba(0, 71, 133, 255)",
    "HUD_COLOUR_SCRIPT_VARIABLE_2" : "rgba(0, 0, 0, 255)",
    "HUD_COLOUR_H" : "rgba(33, 118, 37, 255)",
    "HUD_COLOUR_HDARK" : "rgba(37, 102, 40, 255)",
    "HUD_COLOUR_T" : "rgba(234, 153, 28, 255)",
    "HUD_COLOUR_TDARK" : "rgba(225, 140, 8, 255)",
    "HUD_COLOUR_HSHARD" : "rgba(20, 40, 0, 255)",
    "HUD_COLOUR_CONTROLLER_MICHAEL" : "rgba(48, 255, 255, 255)",
    "HUD_COLOUR_CONTROLLER_FRANKLIN" : "rgba(48, 255, 0, 255)",
    "HUD_COLOUR_CONTROLLER_TREVOR" : "rgba(176, 80, 0, 255)",
    "HUD_COLOUR_CONTROLLER_CHOP" : "rgba(127, 0, 0, 255)",
    "HUD_COLOUR_VIDEO_EDITOR_VIDEO" : "rgba(53, 166, 224, 255)",
    "HUD_COLOUR_VIDEO_EDITOR_AUDIO" : "rgba(162, 79, 157, 255)",
    "HUD_COLOUR_VIDEO_EDITOR_TEXT" : "rgba(104, 192, 141, 255)",
    "HUD_COLOUR_HB_BLUE" : "rgba(29, 100, 153, 255)",
    "HUD_COLOUR_HB_YELLOW" : "rgba(234, 153, 28, 255)",
    "HUD_COLOUR_VIDEO_EDITOR_SCORE" : "rgba(240, 160, 1, 255)",
    "HUD_COLOUR_VIDEO_EDITOR_AUDIO_FADEOUT" : "rgba(59, 34, 57, 255)",
    "HUD_COLOUR_VIDEO_EDITOR_TEXT_FADEOUT" : "rgba(41, 68, 53, 255)",
    "HUD_COLOUR_VIDEO_EDITOR_SCORE_FADEOUT" : "rgba(82, 58, 10, 255)",
    "HUD_COLOUR_HEIST_BACKGROUND" : "rgba(37, 102, 40, 186)",
    "HUD_COLOUR_VIDEO_EDITOR_AMBIENT_FADEOUT" : "rgba(80, 70, 34, 255)",
    "HUD_COLOUR_G1" : "rgba(247, 159, 123, 255)",
    "HUD_COLOUR_G2" : "rgba(226, 134, 187, 255)",
    "HUD_COLOUR_G3" : "rgba(239, 238, 151, 255)",
    "HUD_COLOUR_G4" : "rgba(113, 169, 175, 255)",
    "HUD_COLOUR_G5" : "rgba(160, 140, 193, 255)",
    "HUD_COLOUR_G6" : "rgba(141, 206, 167, 255)",
    "HUD_COLOUR_G7" : "rgba(181, 214, 234, 255)",
    "HUD_COLOUR_G8" : "rgba(178, 144, 132, 255)",
    "HUD_COLOUR_G9" : "rgba(0, 132, 114, 255)",
    "HUD_COLOUR_G10" : "rgba(216, 85, 117, 255)",
    "HUD_COLOUR_G11" : "rgba(30, 100, 152, 255)",
    "HUD_COLOUR_G12" : "rgba(43, 181, 117, 255)",
    "HUD_COLOUR_G13" : "rgba(233, 141, 79, 255)",
    "HUD_COLOUR_G14" : "rgba(137, 210, 215, 255)",
    "HUD_COLOUR_G15" : "rgba(134, 125, 141, 255)",
    "HUD_COLOUR_ADVERSARY" : "rgba(109, 34, 33, 255)",
    "HUD_COLOUR_DEGEN_RED" : "rgba(255, 0, 0, 255)",
    "HUD_COLOUR_DEGEN_YELLOW" : "rgba(255, 255, 0, 255)",
    "HUD_COLOUR_DEGEN_GREEN" : "rgba(0, 255, 0, 255)",
    "HUD_COLOUR_DEGEN_CYAN" : "rgba(0, 255, 255, 255)",
    "HUD_COLOUR_DEGEN_BLUE" : "rgba(0, 0, 255, 255)",
    "HUD_COLOUR_DEGEN_MAGENTA" : "rgba(255, 0, 255, 255)",
    "HUD_COLOUR_STUNT_1" : "rgba(38, 136, 234, 255)",
    "HUD_COLOUR_SPECIAL_RACE_SERIES" : "rgba(154, 178, 54, 255)",
    "HUD_COLOUR_SPECIAL_RACE_SERIES_DARK" : "rgba(93, 107, 45, 255)",
    "HUD_COLOUR_CS" : "rgba(206, 169, 13, 255)",
    "HUD_COLOUR_CS_DARK" : "rgba(103, 84, 6, 255)",
    "HUD_COLOUR_TECH_GREEN" : "rgba(0, 151, 151, 255)",
    "HUD_COLOUR_TECH_GREEN_DARK" : "rgba(5, 119, 113, 255)",
    "HUD_COLOUR_TECH_RED" : "rgba(151, 0, 0, 255)",
    "HUD_COLOUR_TECH_GREEN_VERY_DARK" : "rgba(0, 40, 40, 255)",
    "HUD_COLOUR_PLACEHOLDER_01" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_02" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_03" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_04" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_05" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_06" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_07" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_08" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_09" : "rgba(255, 255, 255, 255)",
    "HUD_COLOUR_PLACEHOLDER_10" : "rgba(255, 255, 255, 255)",
}

const Fonts_modifiers = {
    "h": "font-weight: bold",
    "i": "font-style:italic",
}

const Keys = {'INPUT_NEXT_CAMERA' : 'V',
    'INPUT_LOOK_LR' : 'MOUSE RIGHT',
    'INPUT_LOOK_UD' : 'MOUSE DOWN',
    'INPUT_LOOK_UP_ONLY' : '(NONE)',
    'INPUT_LOOK_DOWN_ONLY' : 'MOUSE DOWN',
    'INPUT_LOOK_LEFT_ONLY' : '(NONE)',
    'INPUT_LOOK_RIGHT_ONLY' : 'MOUSE RIGHT',
    'INPUT_CINEMATIC_SLOWMO' : '(NONE)',
    'INPUT_SCRIPTED_FLY_UD' : 'S',
    'INPUT_SCRIPTED_FLY_LR' : 'D',
    'INPUT_SCRIPTED_FLY_ZUP' : 'PAGEUP',
    'INPUT_SCRIPTED_FLY_ZDOWN' : 'PAGEDOWN',
    'INPUT_WEAPON_WHEEL_UD' : 'MOUSE DOWN',
    'INPUT_WEAPON_WHEEL_LR' : 'MOUSE RIGHT',
    'INPUT_WEAPON_WHEEL_NEXT' : 'SCROLLWHEEL DOWN',
    'INPUT_WEAPON_WHEEL_PREV' : 'SCROLLWHEEL UP',
    'INPUT_SELECT_NEXT_WEAPON' : 'SCROLLWHEEL DOWN',
    'INPUT_SELECT_PREV_WEAPON' : 'SCROLLWHEEL UP',
    'INPUT_SKIP_CUTSCENE' : 'ENTER / LEFT MOUSE BUTTON / SPACEBAR',
    'INPUT_CHARACTER_WHEEL' : 'LEFT ALT',
    'INPUT_MULTIPLAYER_INFO' : 'Z',
    'INPUT_SPRINT' : 'LEFT SHIFT',
    'INPUT_JUMP' : 'SPACEBAR',
    'INPUT_ENTER' : 'F',
    'INPUT_ATTACK' : 'LEFT MOUSE BUTTON',
    'INPUT_AIM' : 'RIGHT MOUSE BUTTON',
    'INPUT_LOOK_BEHIND' : 'C',
    'INPUT_PHONE' : 'ARROW UP / SCROLLWHEEL BUTTON (PRESS)',
    'INPUT_SPECIAL_ABILITY' : '(NONE)',
    'INPUT_SPECIAL_ABILITY_SECONDARY' : 'B',
    'INPUT_MOVE_LR' : 'D',
    'INPUT_MOVE_UD' : 'S',
    'INPUT_MOVE_UP_ONLY' : 'W',
    'INPUT_MOVE_DOWN_ONLY' : 'S',
    'INPUT_MOVE_LEFT_ONLY' : 'A',
    'INPUT_MOVE_RIGHT_ONLY' : 'D',
    'INPUT_DUCK' : 'LEFT CTRL',
    'INPUT_SELECT_WEAPON' : 'TAB',
    'INPUT_PICKUP' : 'E',
    'INPUT_SNIPER_ZOOM' : '[',
    'INPUT_SNIPER_ZOOM_IN_ONLY' : ']',
    'INPUT_SNIPER_ZOOM_OUT_ONLY' : '[',
    'INPUT_SNIPER_ZOOM_IN_SECONDARY' : ']',
    'INPUT_SNIPER_ZOOM_OUT_SECONDARY' : '[',
    'INPUT_COVER' : 'Q',
    'INPUT_RELOAD' : 'R',
    'INPUT_TALK' : 'E',
    'INPUT_DETONATE' : 'G',
    'INPUT_HUD_SPECIAL' : 'Z',
    'INPUT_ARREST' : 'F',
    'INPUT_ACCURATE_AIM' : 'SCROLLWHEEL DOWN',
    'INPUT_CONTEXT' : 'E',
    'INPUT_CONTEXT_SECONDARY' : 'Q',
    'INPUT_WEAPON_SPECIAL' : '(NONE)',
    'INPUT_WEAPON_SPECIAL_TWO' : 'E',
    'INPUT_DIVE' : 'SPACEBAR',
    'INPUT_DROP_WEAPON' : 'F9',
    'INPUT_DROP_AMMO' : 'F10',
    'INPUT_THROW_GRENADE' : 'G',
    'INPUT_VEH_MOVE_LR' : 'D',
    'INPUT_VEH_MOVE_UD' : 'LEFT CTRL',
    'INPUT_VEH_MOVE_UP_ONLY' : 'LEFT SHIFT',
    'INPUT_VEH_MOVE_DOWN_ONLY' : 'LEFT CTRL',
    'INPUT_VEH_MOVE_LEFT_ONLY' : 'A',
    'INPUT_VEH_MOVE_RIGHT_ONLY' : 'D',
    'INPUT_VEH_SPECIAL' : '(NONE)',
    'INPUT_VEH_GUN_LR' : 'MOUSE RIGHT',
    'INPUT_VEH_GUN_UD' : 'MOUSE DOWN',
    'INPUT_VEH_AIM' : 'RIGHT MOUSE BUTTON',
    'INPUT_VEH_ATTACK' : 'LEFT MOUSE BUTTON',
    'INPUT_VEH_ATTACK2' : 'RIGHT MOUSE BUTTON',
    'INPUT_VEH_ACCELERATE' : 'W',
    'INPUT_VEH_BRAKE' : 'S',
    'INPUT_VEH_DUCK' : 'X',
    'INPUT_VEH_HEADLIGHT' : 'H',
    'INPUT_VEH_EXIT' : 'F',
    'INPUT_VEH_HANDBRAKE' : 'SPACEBAR',
    'INPUT_VEH_HOTWIRE_LEFT' : 'W',
    'INPUT_VEH_HOTWIRE_RIGHT' : 'S',
    'INPUT_VEH_LOOK_BEHIND' : 'C',
    'INPUT_VEH_CIN_CAM' : 'R',
    'INPUT_VEH_NEXT_RADIO' : '.',
    'INPUT_VEH_PREV_RADIO' : ',',
    'INPUT_VEH_NEXT_RADIO_TRACK' : '=',
    'INPUT_VEH_PREV_RADIO_TRACK' : '',
    'INPUT_VEH_RADIO_WHEEL' : 'Q',
    'INPUT_VEH_HORN' : 'E',
    'INPUT_VEH_FLY_THROTTLE_UP' : 'W',
    'INPUT_VEH_FLY_THROTTLE_DOWN' : 'S',
    'INPUT_VEH_FLY_YAW_LEFT' : 'A',
    'INPUT_VEH_FLY_YAW_RIGHT' : 'D',
    'INPUT_VEH_PASSENGER_AIM' : 'RIGHT MOUSE BUTTON',
    'INPUT_VEH_PASSENGER_ATTACK' : 'LEFT MOUSE BUTTON',
    'INPUT_VEH_SPECIAL_ABILITY_FRANKLIN' : '(NONE)',
    'INPUT_VEH_STUNT_UD' : '(NONE)',
    'INPUT_VEH_CINEMATIC_UD' : 'MOUSE DOWN',
    'INPUT_VEH_CINEMATIC_UP_ONLY' : 'NUMPAD',
    'INPUT_VEH_CINEMATIC_DOWN_ONLY' : 'NUMPAD+ / SCROLLWHEEL DOWN',
    'INPUT_VEH_CINEMATIC_LR' : 'MOUSE RIGHT',
    'INPUT_VEH_SELECT_NEXT_WEAPON' : 'SCROLLWHEEL UP',
    'INPUT_VEH_SELECT_PREV_WEAPON' : '[',
    'INPUT_VEH_ROOF' : 'H',
    'INPUT_VEH_JUMP' : 'SPACEBAR',
    'INPUT_VEH_GRAPPLING_HOOK' : 'E',
    'INPUT_VEH_SHUFFLE' : 'H',
    'INPUT_VEH_DROP_PROJECTILE' : 'X',
    'INPUT_VEH_MOUSE_CONTROL_OVERRIDE' : 'LEFT MOUSE BUTTON',
    'INPUT_VEH_FLY_ROLL_LR' : 'NUMPAD 6',
    'INPUT_VEH_FLY_ROLL_LEFT_ONLY' : 'NUMPAD 4',
    'INPUT_VEH_FLY_ROLL_RIGHT_ONLY' : 'NUMPAD 6',
    'INPUT_VEH_FLY_PITCH_UD' : 'NUMPAD 5',
    'INPUT_VEH_FLY_PITCH_UP_ONLY' : 'NUMPAD 8',
    'INPUT_VEH_FLY_PITCH_DOWN_ONLY' : 'NUMPAD 5',
    'INPUT_VEH_FLY_UNDERCARRIAGE' : 'G',
    'INPUT_VEH_FLY_ATTACK' : 'RIGHT MOUSE BUTTON',
    'INPUT_VEH_FLY_SELECT_NEXT_WEAPON' : 'SCROLLWHEEL UP',
    'INPUT_VEH_FLY_SELECT_PREV_WEAPON' : '[',
    'INPUT_VEH_FLY_SELECT_TARGET_LEFT' : 'NUMPAD 7',
    'INPUT_VEH_FLY_SELECT_TARGET_RIGHT' : 'NUMPAD 9',
    'INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE' : 'E',
    'INPUT_VEH_FLY_DUCK' : 'X',
    'INPUT_VEH_FLY_ATTACK_CAMERA' : 'INSERT',
    'INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE' : 'LEFT MOUSE BUTTON',
    'INPUT_VEH_SUB_TURN_LR' : 'NUMPAD 6',
    'INPUT_VEH_SUB_TURN_LEFT_ONLY' : 'NUMPAD 4',
    'INPUT_VEH_SUB_TURN_RIGHT_ONLY' : 'NUMPAD 6',
    'INPUT_VEH_SUB_PITCH_UD' : 'NUMPAD 5',
    'INPUT_VEH_SUB_PITCH_UP_ONLY' : 'NUMPAD 8',
    'INPUT_VEH_SUB_PITCH_DOWN_ONLY' : 'NUMPAD 5',
    'INPUT_VEH_SUB_THROTTLE_UP' : 'W',
    'INPUT_VEH_SUB_THROTTLE_DOWN' : 'S',
    'INPUT_VEH_SUB_ASCEND' : 'LEFT SHIFT',
    'INPUT_VEH_SUB_DESCEND' : 'LEFT CTRL',
    'INPUT_VEH_SUB_TURN_HARD_LEFT' : 'A',
    'INPUT_VEH_SUB_TURN_HARD_RIGHT' : 'D',
    'INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE' : 'LEFT MOUSE BUTTON',
    'INPUT_VEH_PUSHBIKE_PEDAL' : 'W',
    'INPUT_VEH_PUSHBIKE_SPRINT' : 'CAPSLOCK',
    'INPUT_VEH_PUSHBIKE_FRONT_BRAKE' : 'Q',
    'INPUT_VEH_PUSHBIKE_REAR_BRAKE' : 'S',
    'INPUT_MELEE_ATTACK_LIGHT' : 'R',
    'INPUT_MELEE_ATTACK_HEAVY' : 'Q',
    'INPUT_MELEE_ATTACK_ALTERNATE' : 'LEFT MOUSE BUTTON',
    'INPUT_MELEE_BLOCK' : 'SPACEBAR',
    'INPUT_PARACHUTE_DEPLOY' : 'F / LEFT MOUSE BUTTON',
    'INPUT_PARACHUTE_DETACH' : 'F',
    'INPUT_PARACHUTE_TURN_LR' : 'D',
    'INPUT_PARACHUTE_TURN_LEFT_ONLY' : 'A',
    'INPUT_PARACHUTE_TURN_RIGHT_ONLY' : 'D',
    'INPUT_PARACHUTE_PITCH_UD' : 'S',
    'INPUT_PARACHUTE_PITCH_UP_ONLY' : 'W',
    'INPUT_PARACHUTE_PITCH_DOWN_ONLY' : 'S',
    'INPUT_PARACHUTE_BRAKE_LEFT' : 'Q',
    'INPUT_PARACHUTE_BRAKE_RIGHT' : 'E',
    'INPUT_PARACHUTE_SMOKE' : 'X',
    'INPUT_PARACHUTE_PRECISION_LANDING' : 'LEFT SHIFT',
    'INPUT_MAP' : '(NONE)',
    'INPUT_SELECT_WEAPON_UNARMED' : '1',
    'INPUT_SELECT_WEAPON_MELEE' : '2',
    'INPUT_SELECT_WEAPON_HANDGUN' : '6',
    'INPUT_SELECT_WEAPON_SHOTGUN' : '3',
    'INPUT_SELECT_WEAPON_SMG' : '7',
    'INPUT_SELECT_WEAPON_AUTO_RIFLE' : '8',
    'INPUT_SELECT_WEAPON_SNIPER' : '9',
    'INPUT_SELECT_WEAPON_HEAVY' : '4',
    'INPUT_SELECT_WEAPON_SPECIAL' : '5',
    'INPUT_SELECT_CHARACTER_MICHAEL' : 'F5',
    'INPUT_SELECT_CHARACTER_FRANKLIN' : 'F6',
    'INPUT_SELECT_CHARACTER_TREVOR' : 'F7',
    'INPUT_SELECT_CHARACTER_MULTIPLAYER' : 'F8 (CONSOLE)',
    'INPUT_SAVE_REPLAY_CLIP' : 'F3',
    'INPUT_SPECIAL_ABILITY_PC' : 'CAPSLOCK',
    'INPUT_CELLPHONE_UP' : 'ARROW UP',
    'INPUT_CELLPHONE_DOWN' : 'ARROW DOWN',
    'INPUT_CELLPHONE_LEFT' : 'ARROW LEFT',
    'INPUT_CELLPHONE_RIGHT' : 'ARROW RIGHT',
    'INPUT_CELLPHONE_SELECT' : 'ENTER / LEFT MOUSE BUTTON',
    'INPUT_CELLPHONE_CANCEL' : 'BACKSPACE / ESC / RIGHT MOUSE BUTTON',
    'INPUT_CELLPHONE_OPTION' : 'DELETE',
    'INPUT_CELLPHONE_EXTRA_OPTION' : 'SPACEBAR',
    'INPUT_CELLPHONE_SCROLL_FORWARD' : 'SCROLLWHEEL DOWN',
    'INPUT_CELLPHONE_SCROLL_BACKWARD' : 'SCROLLWHEEL UP',
    'INPUT_CELLPHONE_CAMERA_FOCUS_LOCK' : 'L',
    'INPUT_CELLPHONE_CAMERA_GRID' : 'G',
    'INPUT_CELLPHONE_CAMERA_SELFIE' : 'E',
    'INPUT_CELLPHONE_CAMERA_DOF' : 'F',
    'INPUT_CELLPHONE_CAMERA_EXPRESSION' : 'X',
    'INPUT_FRONTEND_DOWN' : 'ARROW DOWN',
    'INPUT_FRONTEND_UP' : 'ARROW UP',
    'INPUT_FRONTEND_LEFT' : 'ARROW LEFT',
    'INPUT_FRONTEND_RIGHT' : 'ARROW RIGHT',
    'INPUT_FRONTEND_RDOWN' : 'ENTER',
    'INPUT_FRONTEND_RUP' : 'TAB',
    'INPUT_FRONTEND_RLEFT' : '(NONE)',
    'INPUT_FRONTEND_RRIGHT' : 'BACKSPACE',
    'INPUT_FRONTEND_AXIS_X' : 'D',
    'INPUT_FRONTEND_AXIS_Y' : 'S',
    'INPUT_FRONTEND_RIGHT_AXIS_X' : ']',
    'INPUT_FRONTEND_RIGHT_AXIS_Y' : 'SCROLLWHEEL DOWN',
    'INPUT_FRONTEND_PAUSE' : 'P',
    'INPUT_FRONTEND_PAUSE_ALTERNATE' : 'ESC',
    'INPUT_FRONTEND_ACCEPT' : 'ENTER / NUMPAD ENTER',
    'INPUT_FRONTEND_CANCEL' : 'BACKSPACE / ESC',
    'INPUT_FRONTEND_X' : 'SPACEBAR',
    'INPUT_FRONTEND_Y' : 'TAB',
    'INPUT_FRONTEND_LB' : 'Q',
    'INPUT_FRONTEND_RB' : 'E',
    'INPUT_FRONTEND_LT' : 'PAGE DOWN',
    'INPUT_FRONTEND_RT' : 'PAGE UP',
    'INPUT_FRONTEND_LS' : 'LEFT SHIFT',
    'INPUT_FRONTEND_RS' : 'LEFT CONTROL',
    'INPUT_FRONTEND_LEADERBOARD' : 'TAB',
    'INPUT_FRONTEND_SOCIAL_CLUB' : 'HOME',
    'INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY' : 'HOME',
    'INPUT_FRONTEND_DELETE' : 'DELETE',
    'INPUT_FRONTEND_ENDSCREEN_ACCEPT' : 'ENTER',
    'INPUT_FRONTEND_ENDSCREEN_EXPAND' : 'SPACEBAR',
    'INPUT_FRONTEND_SELECT' : 'CAPSLOCK',
    'INPUT_SCRIPT_LEFT_AXIS_X' : 'D',
    'INPUT_SCRIPT_LEFT_AXIS_Y' : 'S',
    'INPUT_SCRIPT_RIGHT_AXIS_X' : 'MOUSE RIGHT',
    'INPUT_SCRIPT_RIGHT_AXIS_Y' : 'MOUSE DOWN',
    'INPUT_SCRIPT_RUP' : 'RIGHT MOUSE BUTTON',
    'INPUT_SCRIPT_RDOWN' : 'LEFT MOUSE BUTTON',
    'INPUT_SCRIPT_RLEFT' : 'LEFT CTRL',
    'INPUT_SCRIPT_RRIGHT' : 'RIGHT MOUSE BUTTON',
    'INPUT_SCRIPT_LB' : '(NONE)',
    'INPUT_SCRIPT_RB' : '(NONE)',
    'INPUT_SCRIPT_LT' : '(NONE)',
    'INPUT_SCRIPT_RT' : 'LEFT MOUSE BUTTON',
    'INPUT_SCRIPT_LS' : '(NONE)',
    'INPUT_SCRIPT_RS' : '(NONE)',
    'INPUT_SCRIPT_PAD_UP' : 'W',
    'INPUT_SCRIPT_PAD_DOWN' : 'S',
    'INPUT_SCRIPT_PAD_LEFT' : 'A',
    'INPUT_SCRIPT_PAD_RIGHT' : 'D',
    'INPUT_SCRIPT_SELECT' : 'V',
    'INPUT_CURSOR_ACCEPT' : 'LEFT MOUSE BUTTON',
    'INPUT_CURSOR_CANCEL' : 'RIGHT MOUSE BUTTON',
    'INPUT_CURSOR_X' : '(NONE)',
    'INPUT_CURSOR_Y' : '(NONE)',
    'INPUT_CURSOR_SCROLL_UP' : 'SCROLLWHEEL UP',
    'INPUT_CURSOR_SCROLL_DOWN' : 'SCROLLWHEEL DOWN',
    'INPUT_ENTER_CHEAT_CODE' : '~ / `',
    'INPUT_INTERACTION_MENU' : 'M',
    'INPUT_MP_TEXT_CHAT_ALL' : 'T',
    'INPUT_MP_TEXT_CHAT_TEAM' : 'Y',
    'INPUT_MP_TEXT_CHAT_FRIENDS' : '(NONE)',
    'INPUT_MP_TEXT_CHAT_CREW' : '(NONE)',
    'INPUT_PUSH_TO_TALK' : 'N',
    'INPUT_CREATOR_LS' : 'R',
    'INPUT_CREATOR_RS' : 'F',
    'INPUT_CREATOR_LT' : 'X',
    'INPUT_CREATOR_RT' : 'C',
    'INPUT_CREATOR_MENU_TOGGLE' : 'LEFT SHIFT',
    'INPUT_CREATOR_ACCEPT' : 'SPACEBAR',
    'INPUT_CREATOR_DELETE' : 'DELETE',
    'INPUT_ATTACK2' : 'LEFT MOUSE BUTTON',
    'INPUT_RAPPEL_JUMP' : '(NONE)',
    'INPUT_RAPPEL_LONG_JUMP' : '(NONE)',
    'INPUT_RAPPEL_SMASH_WINDOW' : '(NONE)',
    'INPUT_PREV_WEAPON' : 'SCROLLWHEEL UP',
    'INPUT_NEXT_WEAPON' : 'SCROLLWHEEL DOWN',
    'INPUT_MELEE_ATTACK1' : 'R',
    'INPUT_MELEE_ATTACK2' : 'Q',
    'INPUT_WHISTLE' : '(NONE)',
    'INPUT_MOVE_LEFT' : 'D',
    'INPUT_MOVE_RIGHT' : 'D',
    'INPUT_MOVE_UP' : 'S',
    'INPUT_MOVE_DOWN' : 'S',
    'INPUT_LOOK_LEFT' : 'MOUSE RIGHT',
    'INPUT_LOOK_RIGHT' : 'MOUSE RIGHT',
    'INPUT_LOOK_UP' : 'MOUSE DOWN',
    'INPUT_LOOK_DOWN' : 'MOUSE DOWN',
    'INPUT_SNIPER_ZOOM_IN' : '[',
    'INPUT_SNIPER_ZOOM_OUT' : '[',
    'INPUT_SNIPER_ZOOM_IN_ALTERNATE' : '[',
    'INPUT_SNIPER_ZOOM_OUT_ALTERNATE' : '[',
    'INPUT_VEH_MOVE_LEFT' : 'D',
    'INPUT_VEH_MOVE_RIGHT' : 'D',
    'INPUT_VEH_MOVE_UP' : 'LEFT CTRL',
    'INPUT_VEH_MOVE_DOWN' : 'LEFT CTRL',
    'INPUT_VEH_GUN_LEFT' : 'MOUSE RIGHT',
    'INPUT_VEH_GUN_RIGHT' : 'MOUSE RIGHT',
    'INPUT_VEH_GUN_UP' : 'MOUSE RIGHT',
    'INPUT_VEH_GUN_DOWN' : 'MOUSE RIGHT',
    'INPUT_VEH_LOOK_LEFT' : 'MOUSE RIGHT',
    'INPUT_VEH_LOOK_RIGHT' : 'MOUSE RIGHT',
    'INPUT_REPLAY_START_STOP_RECORDING' : 'F1',
    'INPUT_REPLAY_START_STOP_RECORDING_SECONDARY' : 'F2',
    'INPUT_SCALED_LOOK_LR' : 'MOUSE RIGHT',
    'INPUT_SCALED_LOOK_UD' : 'MOUSE DOWN',
    'INPUT_SCALED_LOOK_UP_ONLY' : '(NONE)',
    'INPUT_SCALED_LOOK_DOWN_ONLY' : '(NONE)',
    'INPUT_SCALED_LOOK_LEFT_ONLY' : '(NONE)',
    'INPUT_SCALED_LOOK_RIGHT_ONLY' : '(NONE)',
    'INPUT_REPLAY_MARKER_DELETE' : 'DELETE',
    'INPUT_REPLAY_CLIP_DELETE' : 'DELETE',
    'INPUT_REPLAY_PAUSE' : 'SPACEBAR',
    'INPUT_REPLAY_REWIND' : 'ARROW DOWN',
    'INPUT_REPLAY_FFWD' : 'ARROW UP',
    'INPUT_REPLAY_NEWMARKER' : 'M',
    'INPUT_REPLAY_RECORD' : 'S',
    'INPUT_REPLAY_SCREENSHOT' : 'U',
    'INPUT_REPLAY_HIDEHUD' : 'H',
    'INPUT_REPLAY_STARTPOINT' : 'B',
    'INPUT_REPLAY_ENDPOINT' : 'N',
    'INPUT_REPLAY_ADVANCE' : 'ARROW RIGHT',
    'INPUT_REPLAY_BACK' : 'ARROW LEFT',
    'INPUT_REPLAY_TOOLS' : 'T',
    'INPUT_REPLAY_RESTART' : 'R',
    'INPUT_REPLAY_SHOWHOTKEY' : 'K',
    'INPUT_REPLAY_CYCLEMARKERLEFT' : '[',
    'INPUT_REPLAY_CYCLEMARKERRIGHT' : ']',
    'INPUT_REPLAY_FOVINCREASE' : 'NUMPAD +',
    'INPUT_REPLAY_FOVDECREASE' : 'NUMPAD ',
    'INPUT_REPLAY_CAMERAUP' : 'PAGE UP',
    'INPUT_REPLAY_CAMERADOWN' : 'PAGE DOWN',
    'INPUT_REPLAY_SAVE' : 'F5',
    'INPUT_REPLAY_TOGGLETIME' : 'C',
    'INPUT_REPLAY_TOGGLETIPS' : 'V',
    'INPUT_REPLAY_PREVIEW' : 'SPACEBAR',
    'INPUT_REPLAY_TOGGLE_TIMELINE' : 'ESC',
    'INPUT_REPLAY_TIMELINE_PICKUP_CLIP' : 'X',
    'INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP' : 'C',
    'INPUT_REPLAY_TIMELINE_PLACE_CLIP' : 'V',
    'INPUT_REPLAY_CTRL' : 'LEFT CTRL',
    'INPUT_REPLAY_TIMELINE_SAVE' : 'F5',
    'INPUT_REPLAY_PREVIEW_AUDIO' : 'SPACEBAR',
    'INPUT_VEH_DRIVE_LOOK' : 'LEFT MOUSE BUTTON',
    'INPUT_VEH_DRIVE_LOOK2' : 'RIGHT MOUSE BUTTON',
    'INPUT_VEH_FLY_ATTACK2' : 'RIGHT MOUSE BUTTON',
    'INPUT_RADIO_WHEEL_UD' : 'MOUSE DOWN',
    'INPUT_RADIO_WHEEL_LR' : 'MOUSE RIGHT',
    'INPUT_VEH_SLOWMO_UD' : 'SCROLLWHEEL DOWN',
    'INPUT_VEH_SLOWMO_UP_ONLY' : 'SCROLLWHEEL UP',
    'INPUT_VEH_SLOWMO_DOWN_ONLY' : 'SCROLLWHEEL DOWN',
    'INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE' : 'X',
    'INPUT_VEH_HYDRAULICS_CONTROL_LEFT' : 'A',
    'INPUT_VEH_HYDRAULICS_CONTROL_RIGHT' : 'D',
    'INPUT_VEH_HYDRAULICS_CONTROL_UP' : 'LEFT SHIFT',
    'INPUT_VEH_HYDRAULICS_CONTROL_DOWN' : 'LEFT CTRL',
    'INPUT_VEH_HYDRAULICS_CONTROL_UD' : 'D',
    'INPUT_VEH_HYDRAULICS_CONTROL_LR' : 'LEFT CTRL',
    'INPUT_SWITCH_VISOR' : 'F11',
    'INPUT_VEH_MELEE_HOLD' : 'X',
    'INPUT_VEH_MELEE_LEFT' : 'LEFT MOUSE BUTTON',
    'INPUT_VEH_MELEE_RIGHT' : 'RIGHT MOUSE BUTTON',
    'INPUT_MAP_POI' : 'SCROLLWHEEL BUTTON (PRESS)',
    'INPUT_REPLAY_SNAPMATIC_PHOTO' : 'TAB',
    'INPUT_VEH_CAR_JUMP' : 'E',
    'INPUT_VEH_ROCKET_BOOST' : 'E',
    'INPUT_VEH_FLY_BOOST' : 'LEFT SHIFT',
    'INPUT_VEH_PARACHUTE' : 'SPACEBAR',
    'INPUT_VEH_BIKE_WINGS' : 'X',
    'INPUT_VEH_FLY_BOMB_BAY' : 'E',
    'INPUT_VEH_FLY_COUNTER' : 'E',
    'INPUT_VEH_TRANSFORM' : 'X',
    'INPUT_QUAD_LOCO_REVERSE' : '',
}


const Picture = {
    'CHAR_ABIGAIL' : 'Char_abigail.jpg',
    'CHAR_ACTING_UP' : 'Char_acting_up.jpg',
    'CHAR_AGENT14' : 'Char_agent14.jpg',
    'CHAR_ALL_PLAYERS_CONF' : 'Char_all_players_conf.jpg',
    'CHAR_AMANDA' : 'Char_amanda.jpg',
    'CHAR_AMMUNATION' : 'Char_ammunation.jpg',
    'CHAR_ANDREAS' : 'Char_andreas.jpg',
    'CHAR_ANTONIA' : 'Char_antonia.jpg',
    'CHAR_ARTHUR' : 'Char_arthur.jpg',
    'CHAR_ASHLEY' : 'Char_ashley.jpg',
    'CHAR_BANK_BOL' : 'Char_bank_bol.jpg',
    'CHAR_BANK_FLEECA' : 'Char_bank_fleeca.jpg',
    'CHAR_BANK_MAZE' : 'Char_bank_maze.jpg',
    'CHAR_BARRY' : 'Char_barry.jpg',
    'CHAR_BEVERLY' : 'Char_beverly.jpg',
    'CHAR_BIKESITE' : 'Char_bikesite.jpg',
    'CHAR_BLANK_ENTRY' : 'Char_blank_entry.jpg',
    'CHAR_BLIMP' : 'Char_blimp.jpg',
    'CHAR_BLIMP2' : 'Char_blimp2.jpg',
    'CHAR_BLOCKED' : 'Char_blocked.jpg',
    'CHAR_BOATSITE' : 'Char_boatsite.jpg',
    'CHAR_BOATSITE2' : 'Char_boatsite2.jpg',
    'CHAR_BROKEN_DOWN_GIRL' : 'Char_broken_down_girl.jpg',
    'CHAR_BRYONY' : 'Char_bryony.jpg',
    'CHAR_BUGSTARS' : 'Char_bugstars.jpg',
    'CHAR_CALL911' : 'Char_call911.jpg',
    'CHAR_CARSITE' : 'Char_carsite.jpg',
    'CHAR_CARSITE2' : 'Char_carsite2.jpg',
    'CHAR_CARSITE3' : 'Char_carsite3.jpg',
    'CHAR_CARSITE4' : 'Char_carsite4.jpg',
    'CHAR_CASINO' : 'Char_casino.jpg',
    'CHAR_CASINO_MANAGER' : 'Char_casino_manager.jpg',
    'CHAR_CASTRO' : 'Char_castro.jpg',
    'CHAR_CHAT_CALL' : 'Char_chat_call.jpg',
    'CHAR_CHEF' : 'Char_chef.jpg',
    'CHAR_CHENG' : 'Char_cheng.jpg',
    'CHAR_CHENGSR' : 'Char_chengsr.jpg',
    'CHAR_CHOP' : 'Char_chop.jpg',
    'CHAR_COMIC_STORE' : 'Char_comic_store.jpg',
    'CHAR_CRIS' : 'Char_cris.jpg',
    'CHAR_DAVE' : 'Char_dave.jpg',
    'CHAR_DEFAULT' : 'Char_default.jpg',
    'CHAR_DENISE' : 'Char_denise.jpg',
    'CHAR_DETONATEBOMB' : 'Char_detonatebomb.jpg',
    'CHAR_DETONATEPHONE' : 'Char_detonatephone.jpg',
    'CHAR_DEVIN' : 'Char_devin.jpg',
    'CHAR_DIAL_A_SUB' : 'Char_dial_a_sub.jpg',
    'CHAR_DOM' : 'Char_dom.jpg',
    'CHAR_DOMESTIC_GIRL' : 'Char_domestic_girl.jpg',
    'CHAR_DREYFUSS' : 'Char_dreyfuss.jpg',
    'CHAR_DR_FRIEDLANDER' : 'Char_dr_friedlander.jpg',
    'CHAR_ENGLISH_DAVE' : 'Char_english_dave.jpg',
    'CHAR_EPSILON' : 'Char_epsilon.jpg',
    'CHAR_ESTATE_AGENT' : 'Char_estate_agent.jpg',
    'CHAR_FACEBOOK' : 'Char_facebook.jpg',
    'CHAR_FILMNOIR' : 'Char_filmnoir.jpg',
    'CHAR_FLOYD' : 'Char_floyd.jpg',
    'CHAR_FRANKLIN' : 'Char_franklin.jpg',
    'CHAR_FRANK_TREV_CONF' : 'Char_frank_trev_conf.jpg',
    'CHAR_GANGAPP' : 'Char_gangapp.jpg',
    'CHAR_GAYMILITARY' : 'Char_gaymilitary.jpg',
    'CHAR_HAO' : 'Char_hao.jpg',
    'CHAR_HITCHER_GIRL' : 'Char_hitcher_girl.jpg',
    'CHAR_HUMANDEFAULT' : 'Char_humandefault.jpg',
    'CHAR_HUNTER' : 'Char_hunter.jpg',
    'CHAR_JIMMY' : 'Char_jimmy.jpg',
    'CHAR_JIMMY_BOSTON' : 'Char_jimmy_boston.jpg',
    'CHAR_JOE' : 'Char_joe.jpg',
    'CHAR_JOSEF' : 'Char_josef.jpg',
    'CHAR_JOSH' : 'Char_josh.jpg',
    'CHAR_LAMAR' : 'Char_lamar.jpg',
    'CHAR_LAZLOW' : 'Char_lazlow.jpg',
    'CHAR_LAZLOW2' : 'Char_lazlow2.jpg',
    'CHAR_LESTER' : 'Char_lester.jpg',
    'CHAR_LESTER_DEATHWISH' : 'Char_lester_deathwish.jpg',
    'CHAR_LEST_FRANK_CONF' : 'Char_lest_frank_conf.jpg',
    'CHAR_LEST_MIKE_CONF' : 'Char_lest_mike_conf.jpg',
    'CHAR_LIFEINVADER' : 'Char_lifeinvader.jpg',
    'CHAR_LJT' : 'Char_ljt.jpg',
    'CHAR_LS_CUSTOMS' : 'Char_ls_customs.jpg',
    'CHAR_LS_TOURIST_BOARD' : 'Char_ls_tourist_board.jpg',
    'CHAR_MALC' : 'Char_malc.jpg',
    'CHAR_MANUEL' : 'Char_manuel.jpg',
    'CHAR_MARNIE' : 'Char_marnie.jpg',
    'CHAR_MARTIN' : 'Char_martin.jpg',
    'CHAR_MARY_ANN' : 'Char_mary_ann.jpg',
    'CHAR_MAUDE' : 'Char_maude.jpg',
    'CHAR_MECHANIC' : 'Char_mechanic.jpg',
    'CHAR_MICHAEL' : 'Char_michael.jpg',
    'CHAR_MIKE_FRANK_CONF' : 'Char_mike_frank_conf.jpg',
    'CHAR_MIKE_TREV_CONF' : 'Char_mike_trev_conf.jpg',
    'CHAR_MILSITE' : 'Char_milsite.jpg',
    'CHAR_MINOTAUR' : 'Char_minotaur.jpg',
    'CHAR_MOLLY' : 'Char_molly.jpg',
    'CHAR_MP_ARMY_CONTACT' : 'Char_mp_army_contact.jpg',
    'CHAR_MP_BIKER_BOSS' : 'Char_mp_biker_boss.jpg',
    'CHAR_MP_BIKER_MECHANIC' : 'Char_mp_biker_mechanic.jpg',
    'CHAR_MP_BRUCIE' : 'Char_mp_brucie.jpg',
    'CHAR_MP_DETONATEPHONE' : 'Char_mp_detonatephone.jpg',
    'CHAR_MP_FAM_BOSS' : 'Char_mp_fam_boss.jpg',
    'CHAR_MP_FIB_CONTACT' : 'Char_mp_fib_contact.jpg',
    'CHAR_MP_FM_CONTACT' : 'Char_mp_fm_contact.jpg',
    'CHAR_MP_GERALD' : 'Char_mp_gerald.jpg',
    'CHAR_MP_JULIO' : 'Char_mp_julio.jpg',
    'CHAR_MP_MECHANIC' : 'Char_mp_mechanic.jpg',
    'CHAR_MP_MERRYWEATHER' : 'Char_mp_merryweather.jpg',
    'CHAR_MP_MEX_BOSS' : 'Char_mp_mex_boss.jpg',
    'CHAR_MP_MEX_DOCKS' : 'Char_mp_mex_docks.jpg',
    'CHAR_MP_MEX_LT' : 'Char_mp_mex_lt.jpg',
    'CHAR_MP_MORS_MUTUAL' : 'Char_mp_mors_mutual.jpg',
    'CHAR_MP_PROF_BOSS' : 'Char_mp_prof_boss.jpg',
    'CHAR_MP_RAY_LAVOY' : 'Char_mp_ray_lavoy.jpg',
    'CHAR_MP_ROBERTO' : 'Char_mp_roberto.jpg',
    'CHAR_MP_SNITCH' : 'Char_mp_snitch.jpg',
    'CHAR_MP_STRETCH' : 'Char_mp_stretch.jpg',
    'CHAR_MP_STRIPCLUB_PR' : 'Char_mp_stripclub_pr.jpg',
    'CHAR_MRS_THORNHILL' : 'Char_mrs_thornhill.jpg',
    'CHAR_MULTIPLAYER' : 'Char_multiplayer.jpg',
    'CHAR_NIGEL' : 'Char_nigel.jpg',
    'CHAR_OMEGA' : 'Char_omega.jpg',
    'CHAR_ONEIL' : 'Char_oneil.jpg',
    'CHAR_ORTEGA' : 'Char_ortega.jpg',
    'CHAR_OSCAR' : 'Char_oscar.jpg',
    'CHAR_PAIGE' : 'Char_paige.jpg',
    'CHAR_PATRICIA' : 'Char_patricia.jpg',
    'CHAR_PA_FEMALE' : 'Char_pa_female.jpg',
    'CHAR_PA_MALE' : 'Char_pa_male.jpg',
    'CHAR_PEGASUS_DELIVERY' : 'Char_pegasus_delivery.jpg',
    'CHAR_PLANESITE' : 'Char_planesite.jpg',
    'CHAR_PROPERTY_ARMS_TRAFFICKING' : 'Char_property_arms_trafficking.jpg',
    'CHAR_PROPERTY_BAR_AIRPORT' : 'Char_property_bar_airport.jpg',
    'CHAR_PROPERTY_BAR_BAYVIEW' : 'Char_property_bar_bayview.jpg',
    'CHAR_PROPERTY_BAR_CAFE_ROJO' : 'Char_property_bar_cafe_rojo.jpg',
    'CHAR_PROPERTY_BAR_COCKOTOOS' : 'Char_property_bar_cockotoos.jpg',
    'CHAR_PROPERTY_BAR_FES' : 'Char_property_bar_fes.jpg',
    'CHAR_PROPERTY_BAR_HEN_HOUSE' : 'Char_property_bar_hen_house.jpg',
    'CHAR_PROPERTY_BAR_IRISH' : 'Char_property_bar_irish.jpg',
    'CHAR_PROPERTY_BAR_LES_BIANCO' : 'Char_property_bar_les_bianco.jpg',
    'CHAR_PROPERTY_BAR_MIRROR_PARK' : 'Char_property_bar_mirror_park.jpg',
    'CHAR_PROPERTY_BAR_TEQUILALA' : 'Char_property_bar_tequilala.jpg',
    'CHAR_PROPERTY_CAR_MOD_SHOP' : 'Char_property_car_mod_shop.jpg',
    'CHAR_PROPERTY_CAR_SCRAP_YARD' : 'Char_property_car_scrap_yard.jpg',
    'CHAR_PROPERTY_CINEMA_VINEWOOD' : 'Char_property_cinema_vinewood.jpg',
    'CHAR_PROPERTY_PLANE_SCRAP_YARD' : 'Char_property_plane_scrap_yard.jpg',
    'CHAR_PROPERTY_SONAR_COLLECTIONS' : 'Char_property_sonar_collections.jpg',
    'CHAR_RICKIE' : 'Char_rickie.jpg',
    'CHAR_RON' : 'Char_ron.jpg',
    'CHAR_SASQUATCH' : 'Char_sasquatch.jpg',
    'CHAR_SOCIAL_CLUB' : 'Char_social_club.jpg',
    'CHAR_SOLOMON' : 'Char_solomon.jpg',
    'CHAR_STEVE_MIKE_CONF' : 'Char_steve_mike_conf.jpg',
    'CHAR_STEVE_TREV_CONF' : 'Char_steve_trev_conf.jpg',
    'CHAR_STRETCH' : 'Char_stretch.jpg',
    'CHAR_STRIPPER_CHASTITY' : 'Char_stripper_chastity.jpg',
    'CHAR_STRIPPER_FUFU' : 'Char_stripper_fufu.jpg',
    'CHAR_STRIPPER_PEACH' : 'Char_stripper_peach.jpg',
    'CHAR_STRIPPER_SAPPHIRE' : 'Char_stripper_sapphire.jpg',
    'CHAR_TANISHA' : 'Char_tanisha.jpg',
    'CHAR_TAOTRANSLATOR' : 'Char_taotranslator.jpg',
    'CHAR_TAXI' : 'Char_taxi.jpg',
    'CHAR_TAXI_LIZ' : 'Char_taxi_liz.jpg',
    'CHAR_TOW_TONYA' : 'Char_tow_tonya.jpg',
    'CHAR_TREVOR' : 'Char_trevor.jpg',
    'CHAR_WADE' : 'Char_wade.jpg',
    'CHAR_WENDY' : 'Char_wendy.jpg',
    'DIA_AH1_JANITOR' : 'Dia_ah1_janitor.jpg',
    'DIA_AH2_ARCHITECT' : 'Dia_ah2_architect.jpg',
    'DIA_ANTON' : 'Dia_anton.jpg',
    'DIA_ARMY' : 'Dia_army.jpg',
    'DIA_AVI' : 'Dia_avi.jpg',
    'DIA_CASEY' : 'Dia_casey.jpg',
    'DIA_CUSTOMER' : 'Dia_customer.jpg',
    'DIA_DEALER' : 'Dia_dealer.jpg',
    'DIA_GARDENING' : 'Dia_gardening.jpg',
    'DIA_GUIDO' : 'Dia_guido.jpg',
    'DIA_HEIJETSKI' : 'Dia_heijetski.jpg',
    'DIA_HUANG' : 'Dia_huang.jpg',
    'DIA_JANET' : 'Dia_janet.jpg',
    'DIA_JEROME' : 'Dia_jerome.jpg',
    'DIA_JESUS' : 'Dia_jesus.jpg',
    'DIA_JETPILOT' : 'Dia_jetpilot.jpg',
    'DIA_KENNETH' : 'Dia_kenneth.jpg',
    'DIA_LOVEFIST' : 'Dia_lovefist.jpg',
    'DIA_MRSR' : 'Dia_mrsr.jpg',
    'DIA_NATALIA' : 'Dia_natalia.jpg',
    'DIA_OJBB3_XMECH' : 'Dia_ojbb3_xmech.jpg',
    'DIA_PILOT' : 'Dia_pilot.jpg',
    'DIA_POPOV' : 'Dia_popov.jpg',
    'DIA_POPPYMICH' : 'Dia_poppymich.jpg',
    'DIA_PRINCESS' : 'Dia_princess.jpg',
    'DIA_PRO1_CLERGY' : 'Dia_pro1_clergy.jpg',
    'DIA_PRO1_HOSTF1' : 'Dia_pro1_hostf1.jpg',
    'DIA_RE31A_AIRPORT' : 'Dia_re31a_airport.jpg',
    'DIA_SAS1_HUNTER' : 'Dia_sas1_hunter.jpg',
    'DIA_SCIENTIST' : 'Dia_scientist.jpg',
    'DIA_SHOP' : 'Dia_shop.jpg',
    'DIA_TANNOY' : 'Dia_tannoy.jpg',
    'DIA_TENNIS' : 'Dia_tennis.jpg',
    'DIA_TERRY' : 'Dia_terry.jpg',
    'DIA_TOUR' : 'Dia_tour.jpg',
    'DIA_TOURIST' : 'Dia_tourist.jpg',
    'DIA_TYLERDIX' : 'Dia_tylerdix.jpg',
    'DIA_ULP' : 'Dia_ulp.jpg',
    'DIA_VICTIM' : 'Dia_victim.jpg',
    'DIA_WILLY' : 'Dia_willy.jpg',
    'DIA_ZOMBIE1' : 'Dia_zombie1.jpg',
    'HC_N_CHE' : 'Hc_n_che.jpg',
    'HC_N_DAR' : 'Hc_n_dar.jpg',
    'HC_N_EDD' : 'Hc_n_edd.jpg',
    'HC_N_FRANKLIN' : 'Hc_n_franklin.jpg',
    'HC_N_GET' : 'Hc_n_get.jpg',
    'HC_N_GUS' : 'Hc_n_gus.jpg',
    'HC_N_HUG' : 'Hc_n_hug.jpg',
    'HC_N_KAR' : 'Hc_n_kar.jpg',
    'HC_N_MICHAEL' : 'Hc_n_michael.jpg',
    'WEB_ACCOUNTANTTVSHOW' : 'Web_accountanttvshow.jpg',
    'WEB_ALDINAPOLI' : 'Web_aldinapoli.jpg',
    'WEB_BARBEQUESPACEFLIGHT' : 'Web_barbequespaceflight.jpg',
    'WEB_BITTERSWEETCELLPHONE' : 'Web_bittersweetcellphone.jpg',
    'WEB_BRUCESPADE' : 'Web_brucespade.jpg',
    'WEB_CASHFORDEADDREAMS' : 'Web_cashfordeaddreams.jpg',
    'WEB_CHADMULLIGAN' : 'Web_chadmulligan.jpg',
    'WEB_CHUMASH_KIKI' : 'Web_chumash_kiki.jpg',
    'WEB_CREDITCARDCONSOLIDATIONKINGS' : 'Web_creditcardconsolidationkings.jpg',
    'WEB_CREVISOUTDOORAPPAREL' : 'Web_crevisoutdoorapparel.jpg',
    'WEB_CUNNINGSTUNTACADEMY' : 'Web_cunningstuntacademy.jpg',
    'WEB_FAMEORSHAME' : 'Web_fameorshame.jpg',
    'WEB_FEARFIRST' : 'Web_fearfirst.jpg',
    'WEB_FRUIT' : 'Web_fruit.jpg',
    'WEB_GERALDINOK6' : 'Web_geraldinok6.jpg',
    'WEB_KERRYMCINTOSH' : 'Web_kerrymcintosh.jpg',
    'WEB_LONNIE_FIG3' : 'Web_lonnie_fig3.jpg',
    'WEB_MANOLODEORO2' : 'Web_manolodeoro2.jpg',
    'WEB_POUNDERSFOOTBALL' : 'Web_poundersfootball.jpg',
    'WEB_POWCLEANSE' : 'Web_powcleanse.jpg',
    'WEB_RECYCLEHUGO17' : 'Web_recyclehugo17.jpg',
    'WEB_RIGHT4EVA' : 'Web_right4eva.jpg',
    'WEB_SWINGERSBASEBALL' : 'Web_swingersbaseball.jpg',
    'WEB_TONYMCTONY' : 'Web_tonymctony.jpg',
    'WEB_VINEWOODLIONEL67' : 'Web_vinewoodlionel67.jpg',
    'WEB_YOURNEWBABYSNAME' : 'Web_yournewbabysname.jpg',
    "MESSAGE" : "message.png"
}
