/*
 * Copyright (c) 2023 ADN's. All right reserved.
 */

var REF_HELPNOTIFICATION_CONTAINER;
var REF_NOTIFICATION_CONTAINER;


var REF_HELPNOTIFICATION_CONTAINER_RIGHT = document.getElementById("HELPNOTIFICATION-CONTAINER-RIGHT");
var REF_NOTIFICATION_CONTAINER_RIGHT = document.getElementById("NOTIFICATION-CONTAINER-RIGHT");
var REF_HELPNOTIFICATION_CONTAINER_LEFT = document.getElementById("HELPNOTIFICATION-CONTAINER-LEFT");
var REF_NOTIFICATION_CONTAINER_LEFT = document.getElementById("NOTIFICATION-CONTAINER-LEFT");
var REF_HELPNOTIFICATION_CONTAINER_MIDDLE = document.getElementById("HELPNOTIFICATION-CONTAINER-MIDDLE");
var REF_NOTIFICATION_CONTAINER_MIDDLE = document.getElementById("NOTIFICATION-CONTAINER-MIDDLE");
