---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 21/04/2019 21:20
---

---round
---@param num number
---@param numDecimalPlaces number
---@return number
---@public
function math.round(num, numDecimalPlaces)
    return tonumber(string.format("%." .. (numDecimalPlaces or 0) .. "f", num))
end

---starts
---@param String string
---@param Start number
---@return number
---@public
function string.starts(String, Start)
    return string.sub(String, 1, string.len(Start)) == Start
end

---@type table
FlashSideUI.Menus = setmetatable({}, FlashSideUI.Menus)

---@type table
---@return boolean
FlashSideUI.Menus.__call = function()
    return true
end

---@type table
FlashSideUI.Menus.__index = FlashSideUI.Menus

---@type table
FlashSideUI.CurrentMenu = nil

---@type table
FlashSideUI.NextMenu = nil

---@type number
FlashSideUI.Options = 0

---@type number
FlashSideUI.ItemOffset = 0

---@type number
FlashSideUI.StatisticPanelCount = 0

---@type table
FlashSideUI.UI = {
    Current = "FlashSideUI",
    Style = {
        FlashSideUI = {
            Width = 100
        },
        NativeUI = {
            Width = 0
        }
    }
}

---@type table
FlashSideUI.Settings = {
    Debug = false,
    Controls = {
        Up = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 172 },
                { 1, 172 },
                { 2, 172 },
                { 0, 241 },
                { 1, 241 },
                { 2, 241 },
            },
        },
        Down = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 173 },
                { 1, 173 },
                { 2, 173 },
                { 0, 242 },
                { 1, 242 },
                { 2, 242 },
            },
        },
        Left = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        Right = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        SliderLeft = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        SliderRight = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        Select = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 201 },
                { 1, 201 },
                { 2, 201 },
            },
        },
        Back = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 177 },
                { 1, 177 },
                { 2, 177 },
                { 0, 199 },
                { 1, 199 },
                { 2, 199 },
            },
        },
        Click = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 24 },
            },
        },
        Enabled = {
            Controller = {
                { 0, 2 }, -- Look Up and Down
                { 0, 1 }, -- Look Left and Right
                { 0, 25 }, -- Aim
                { 0, 24 }, -- Attack
            },
            Keyboard = {
                { 0, 201 }, -- Select
                { 0, 195 }, -- X axis
                { 0, 196 }, -- Y axis
                { 0, 187 }, -- Down
                { 0, 188 }, -- Up
                { 0, 189 }, -- Left
                { 0, 190 }, -- Right
                { 0, 202 }, -- Back
                { 0, 217 }, -- Select
                { 0, 242 }, -- Scroll down
                { 0, 241 }, -- Scroll up
                { 0, 239 }, -- Cursor X
                { 0, 240 }, -- Cursor Y
                { 0, 31 }, -- Move Up and Down
                { 0, 30 }, -- Move Left and Right
                { 0, 21 }, -- Sprint
                { 0, 22 }, -- Jump
                { 0, 23 }, -- Enter
                { 0, 75 }, -- Exit Vehicle
                { 0, 71 }, -- Accelerate Vehicle
                { 0, 72 }, -- Vehicle Brake
                { 0, 59 }, -- Move Vehicle Left and Right
                { 0, 89 }, -- Fly Yaw Left
                { 0, 9 }, -- Fly Left and Right
                { 0, 8 }, -- Fly Up and Down
                { 0, 90 }, -- Fly Yaw Right
                { 0, 76 }, -- Vehicle Handbrake
            },
        },
    },
    Audio = {
        Id = nil,
        Use = "FlashSideUI",
        FlashSideUI = {
            UpDown = {
                audioName = "HUD_FREEMODE_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        },
        NativeUI = {
            UpDown = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        }
    },
    Items = {
        Title = {
            Background = { Width = 431, Height = 107 },
            Text = { X = 215, Y = 20, Scale = 1.15 },
        },
        Subtitle = {
            Background = { Width = 431, Height = 37 },
            Text = { X = 8, Y = 3, Scale = 0.25 },
            PreText = { X = 425, Y = 3, Scale = 0.25 },
        },
        Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0, Width = 431 },
        Navigation = {
            Rectangle = { Width = 431, Height = 18 },
            Offset = 5,
            Arrows = { Dictionary = "commonmenu", Texture = "shop_arrows_upanddown", X = 190, Y = -6, Width = 50, Height = 50 },
        },
        Description = {
            Bar = { Y = 4, Width = 431, Height = 4 },
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 30 },
            Text = { X = 8, Y = 10, Scale = 0.25 },
        },
    },
    Panels = {
        Grid = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 275 },
            Grid = { Dictionary = "pause_menu_pages_char_mom_dad", Texture = "nose_grid", X = 115.5, Y = 47.5, Width = 200, Height = 200 },
            Circle = { Dictionary = "mpinventory", Texture = "in_world_circle", X = 115.5, Y = 47.5, Width = 20, Height = 20 },
            Text = {
                Top = { X = 215.5, Y = 15, Scale = 0.25 },
                Bottom = { X = 215.5, Y = 250, Scale = 0.25 },
                Left = { X = 57.75, Y = 130, Scale = 0.25 },
                Right = { X = 373.25, Y = 130, Scale = 0.25 },
            },
        },
        Percentage = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 76 },
            Bar = { X = 9, Y = 50, Width = 413, Height = 10 },
            Text = {
                Left = { X = 25, Y = 15, Scale = 0.25 },
                Middle = { X = 215.5, Y = 15, Scale = 0.25 },
                Right = { X = 398, Y = 15, Scale = 0.25 },
            },
        },
    },
}

function FlashSideUI.SetScaleformParams(scaleform, data)
    data = data or {}
    for k, v in pairs(data) do
        PushScaleformMovieFunction(scaleform, v.name)
        if v.param then
            for _, par in pairs(v.param) do
                if math.type(par) == "integer" then
                    PushScaleformMovieFunctionParameterInt(par)
                elseif type(par) == "boolean" then
                    PushScaleformMovieFunctionParameterBool(par)
                elseif math.type(par) == "float" then
                    PushScaleformMovieFunctionParameterFloat(par)
                elseif type(par) == "string" then
                    PushScaleformMovieFunctionParameterString(par)
                end
            end
        end
        if v.func then
            v.func()
        end
        PopScaleformMovieFunctionVoid()
    end
end

---Visible
---@param Menu function
---@param Value boolean
---@return table
---@public
function FlashSideUI.Visible(Menu, Value)
    if Menu ~= nil then
        if Menu() then
            if type(Value) == "boolean" then
                if Value then
                    if FlashSideUI.CurrentMenu ~= nil then
                        FlashSideUI.CurrentMenu.Closed()
                        FlashSideUI.CurrentMenu.Open = not Value
                    end
                    Menu:UpdateInstructionalButtons(Value);
                    Menu:UpdateCursorStyle();
                    FlashSideUI.CurrentMenu = Menu
                    menuOpen = true
                else
                    menuOpen = false
                    FlashSideUI.CurrentMenu = nil
                end
                Menu.Open = Value
                FlashSideUI.Options = 0
                FlashSideUI.ItemOffset = 0
                FlashSideUI.LastControl = false
            else
                return Menu.Open
            end
        end
    end
end 

function FlashSideUI.CloseAll()
    menuOpen = false

    if FlashSideUI.CurrentMenu ~= nil then
        local parent = FlashSideUI.CurrentMenu.Parent
        while parent ~= nil do
            parent.Index = 1
            parent.Pagination.Minimum = 1
            parent.Pagination.Maximum = 10
            parent = parent.Parent
        end
        FlashSideUI.CurrentMenu.Index = 1
        FlashSideUI.CurrentMenu.Pagination.Minimum = 1
        FlashSideUI.CurrentMenu.Pagination.Maximum = 10
        FlashSideUI.CurrentMenu.Open = false
        FlashSideUI.CurrentMenu = nil
    end
    FlashSideUI.Options = 0
    FlashSideUI.ItemOffset = 0
    ResetScriptGfxAlign()
end

---Banner
---@return nil
---@public
---@param Enabled boolean
function FlashSideUI.Banner(Enabled, Glare)
    if type(Enabled) == "boolean" then
        if Enabled == true then


            if FlashSideUI.CurrentMenu ~= nil then
                if FlashSideUI.CurrentMenu() then


                    FlashSideUI.ItemsSafeZone(FlashSideUI.CurrentMenu)

                    if FlashSideUI.CurrentMenu.Sprite then
                        RenderSprite(FlashSideUI.CurrentMenu.Sprite.Dictionary, FlashSideUI.CurrentMenu.Sprite.Texture, FlashSideUI.CurrentMenu.X, FlashSideUI.CurrentMenu.Y, FlashSideUI.Settings.Items.Title.Background.Width + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.Settings.Items.Title.Background.Height, nil)
                    else
                        RenderRectangle(FlashSideUI.CurrentMenu.X, FlashSideUI.CurrentMenu.Y, FlashSideUI.Settings.Items.Title.Background.Width + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.Settings.Items.Title.Background.Height, FlashSideUI.CurrentMenu.Rectangle.R, FlashSideUI.CurrentMenu.Rectangle.G, FlashSideUI.CurrentMenu.Rectangle.B, FlashSideUI.CurrentMenu.Rectangle.A)
                    end

                    --if (FlashSideUI.CurrentMenu.WidthOffset == 100) then
                        if Glare then

                            local ScaleformMovie = RequestScaleformMovie("MP_MENU_GLARE")
                            while not HasScaleformMovieLoaded(ScaleformMovie) do
                                Citizen.Wait(0)
                            end

							---@type number
							local Glarewidth = FlashSideUI.Settings.Items.Title.Background.Width

							---@type number
							local Glareheight = FlashSideUI.Settings.Items.Title.Background.Height
							---@type number
							local GlareX = FlashSideUI.CurrentMenu.X / 1860 + (FlashSideUI.CurrentMenu.SafeZoneSize.X / (64.399 - (FlashSideUI.CurrentMenu.WidthOffset * 0.065731)))
                            ---@type number
                            local GlareY = FlashSideUI.CurrentMenu.Y / 1080 + FlashSideUI.CurrentMenu.SafeZoneSize.Y / 33.195020746888
                            FlashSideUI.SetScaleformParams(ScaleformMovie, {
                                { name = "SET_DATA_SLOT", param = { GetGameplayCamRelativeHeading() } }
                            })

                            DrawScaleformMovie(ScaleformMovie, GlareX, GlareY, Glarewidth / 430, Glareheight / 100, 255, 255, 255, 255, 0)

                        end
                    --end

                    RenderText(FlashSideUI.CurrentMenu.Title, FlashSideUI.CurrentMenu.X + FlashSideUI.Settings.Items.Title.Text.X + (FlashSideUI.CurrentMenu.WidthOffset / 2), FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Title.Text.Y, 1, FlashSideUI.Settings.Items.Title.Text.Scale, 255, 255, 255, 255, 1)
                    FlashSideUI.ItemOffset = FlashSideUI.ItemOffset + FlashSideUI.Settings.Items.Title.Background.Height
                end
            end
        end
    else
        error("Enabled is not boolean")
    end
end

---CloseAll -- TODO 
---@return nil
---@public
-- function FlashSideUI:CloseAll()
--     FlashSideUI.PlaySound(FlashSideUI.Settings.Audio.Library, FlashSideUI.Settings.Audio.Back)
--     FlashSideUI.NextMenu = nil
--     FlashSideUI.Visible(FlashSideUI.CurrentMenu, false)
-- end

---Subtitle
---@return nil
---@public
function FlashSideUI.Subtitle()
    if FlashSideUI.CurrentMenu ~= nil then
        if FlashSideUI.CurrentMenu() then
            FlashSideUI.ItemsSafeZone(FlashSideUI.CurrentMenu)
            if FlashSideUI.CurrentMenu.Subtitle ~= "" then
                RenderRectangle(FlashSideUI.CurrentMenu.X, FlashSideUI.CurrentMenu.Y + FlashSideUI.ItemOffset, FlashSideUI.Settings.Items.Subtitle.Background.Width + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.Settings.Items.Subtitle.Background.Height + FlashSideUI.CurrentMenu.SubtitleHeight, 0, 0, 0, 255)
                RenderText(FlashSideUI.CurrentMenu.Subtitle, FlashSideUI.CurrentMenu.X + FlashSideUI.Settings.Items.Subtitle.Text.X, FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Subtitle.Text.Y + FlashSideUI.ItemOffset, 0, FlashSideUI.Settings.Items.Subtitle.Text.Scale, 245, 245, 245, 255, nil, false, false, FlashSideUI.Settings.Items.Subtitle.Background.Width + FlashSideUI.CurrentMenu.WidthOffset)
                if FlashSideUI.CurrentMenu.Index > FlashSideUI.CurrentMenu.Options or FlashSideUI.CurrentMenu.Index < 0 then
                    FlashSideUI.CurrentMenu.Index = 1
                end
                FlashSideUI.RefreshPagination()
                if FlashSideUI.CurrentMenu.PageCounter == nil then
                    RenderText(FlashSideUI.CurrentMenu.PageCounterColour .. FlashSideUI.CurrentMenu.Index .. " / " .. FlashSideUI.CurrentMenu.Options, FlashSideUI.CurrentMenu.X + FlashSideUI.Settings.Items.Subtitle.PreText.X + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Subtitle.PreText.Y + FlashSideUI.ItemOffset, 0, FlashSideUI.Settings.Items.Subtitle.PreText.Scale, 245, 245, 245, 255, 2)
                else
                    RenderText(FlashSideUI.CurrentMenu.PageCounter, FlashSideUI.CurrentMenu.X + FlashSideUI.Settings.Items.Subtitle.PreText.X + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Subtitle.PreText.Y + FlashSideUI.ItemOffset, 0, FlashSideUI.Settings.Items.Subtitle.PreText.Scale, 245, 245, 245, 255, 2)
                end
                FlashSideUI.ItemOffset = FlashSideUI.ItemOffset + FlashSideUI.Settings.Items.Subtitle.Background.Height
            end
        end
    end
end

---Background
---@return nil
---@public
function FlashSideUI.Background()
    if FlashSideUI.CurrentMenu ~= nil then
        if FlashSideUI.CurrentMenu() then
            FlashSideUI.ItemsSafeZone(FlashSideUI.CurrentMenu)
            SetScriptGfxDrawOrder(0)
            RenderSprite(FlashSideUI.Settings.Items.Background.Dictionary, FlashSideUI.Settings.Items.Background.Texture, FlashSideUI.CurrentMenu.X, FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Background.Y + FlashSideUI.CurrentMenu.SubtitleHeight, FlashSideUI.Settings.Items.Background.Width + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.ItemOffset, 0, 0, 0, 0, 255)
            SetScriptGfxDrawOrder(1)
        end
    end
end

---Description
---@return nil
---@public
function FlashSideUI.Description()
    if FlashSideUI.CurrentMenu ~= nil and FlashSideUI.CurrentMenu.Description ~= nil then
        if FlashSideUI.CurrentMenu() then
            FlashSideUI.ItemsSafeZone(FlashSideUI.CurrentMenu)
            RenderRectangle(FlashSideUI.CurrentMenu.X, FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Description.Bar.Y + FlashSideUI.CurrentMenu.SubtitleHeight + FlashSideUI.ItemOffset, FlashSideUI.Settings.Items.Description.Bar.Width + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.Settings.Items.Description.Bar.Height, 0, 0, 0, 255)
            RenderSprite(FlashSideUI.Settings.Items.Description.Background.Dictionary, FlashSideUI.Settings.Items.Description.Background.Texture, FlashSideUI.CurrentMenu.X, FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Description.Background.Y + FlashSideUI.CurrentMenu.SubtitleHeight + FlashSideUI.ItemOffset, FlashSideUI.Settings.Items.Description.Background.Width + FlashSideUI.CurrentMenu.WidthOffset, FlashSideUI.CurrentMenu.DescriptionHeight, 0, 0, 0, 255)
            RenderText(FlashSideUI.CurrentMenu.Description, FlashSideUI.CurrentMenu.X + FlashSideUI.Settings.Items.Description.Text.X, FlashSideUI.CurrentMenu.Y + FlashSideUI.Settings.Items.Description.Text.Y + FlashSideUI.CurrentMenu.SubtitleHeight + FlashSideUI.ItemOffset, 0, FlashSideUI.Settings.Items.Description.Text.Scale, 255, 255, 255, 255, nil, false, false, FlashSideUI.Settings.Items.Description.Background.Width + FlashSideUI.CurrentMenu.WidthOffset - 8.0)
            FlashSideUI.ItemOffset = FlashSideUI.ItemOffset + FlashSideUI.CurrentMenu.DescriptionHeight + FlashSideUI.Settings.Items.Description.Bar.Y
        end
    end
end

---Render
---@param instructionalButton boolean
---@return nil
---@public
function FlashSideUI.Render(instructionalButton)
    if FlashSideUI.CurrentMenu ~= nil then
        if FlashSideUI.CurrentMenu() then
            if FlashSideUI.CurrentMenu.Safezone then
                ResetScriptGfxAlign()
            end
            if (instructionalButton) then
                DrawScaleformMovieFullscreen(FlashSideUI.CurrentMenu.InstructionalScaleform, 255, 255, 255, 255, 0)
            end
            FlashSideUI.CurrentMenu.Options = FlashSideUI.Options
            FlashSideUI.CurrentMenu.SafeZoneSize = nil
            FlashSideUI.Controls()
            FlashSideUI.Options = 0
            FlashSideUI.StatisticPanelCount = 0
            FlashSideUI.ItemOffset = 0
            if FlashSideUI.CurrentMenu.Controls.Back.Enabled and FlashSideUI.CurrentMenu.Closable then
                if FlashSideUI.CurrentMenu.Controls.Back.Pressed then
                    FlashSideUI.CurrentMenu.Controls.Back.Pressed = false
                    local Audio = FlashSideUI.Settings.Audio
                    FlashSideUI.PlaySound(Audio[Audio.Use].Back.audioName, Audio[Audio.Use].Back.audioRef)
                    if FlashSideUI.CurrentMenu.Closed ~= nil then
                        collectgarbage()
                        FlashSideUI.CurrentMenu.Closed()
                    end
                    if FlashSideUI.CurrentMenu.Parent ~= nil then
                        if FlashSideUI.CurrentMenu.Parent() then
                            FlashSideUI.NextMenu = FlashSideUI.CurrentMenu.Parent
                            FlashSideUI.CurrentMenu:UpdateCursorStyle()
                        else
                            --print('xxx') Debug print
                            FlashSideUI.NextMenu = nil
                            FlashSideUI.Visible(FlashSideUI.CurrentMenu, false)
                        end
                    else
                        --print('zz') Debug print
                        FlashSideUI.NextMenu = nil
                        FlashSideUI.Visible(FlashSideUI.CurrentMenu, false)
                    end
                end
            end
            if FlashSideUI.NextMenu ~= nil then
                if FlashSideUI.NextMenu() then
                    FlashSideUI.Visible(FlashSideUI.CurrentMenu, false)
                    FlashSideUI.Visible(FlashSideUI.NextMenu, true)
                    FlashSideUI.CurrentMenu.Controls.Select.Active = false
                    FlashSideUI.NextMenu = nil
                    FlashSideUI.LastControl = false
                end
            end
        end
    end
end

---ItemsDescription
---@param CurrentMenu table
---@param Description string
---@param Selected boolean
---@return nil
---@public
function FlashSideUI.ItemsDescription(CurrentMenu, Description, Selected)
    ---@type table
    if Description ~= "" or Description ~= nil then
        local SettingsDescription = FlashSideUI.Settings.Items.Description;
        if Selected and CurrentMenu.Description ~= Description then
            CurrentMenu.Description = Description or nil
            ---@type number
            local DescriptionLineCount = GetLineCount(CurrentMenu.Description, CurrentMenu.X + SettingsDescription.Text.X, CurrentMenu.Y + SettingsDescription.Text.Y + CurrentMenu.SubtitleHeight + FlashSideUI.ItemOffset, 0, SettingsDescription.Text.Scale, 255, 255, 255, 255, nil, false, false, SettingsDescription.Background.Width + (CurrentMenu.WidthOffset - 5.0))
            if DescriptionLineCount > 1 then
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height * DescriptionLineCount
            else
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height + 7
            end
        end
    end
end

---MouseBounds
---@param CurrentMenu table
---@param Selected boolean
---@param Option number
---@param SettingsButton table
---@return boolean
---@public
function FlashSideUI.ItemsMouseBounds(CurrentMenu, Selected, Option, SettingsButton)
    ---@type boolean
    local Hovered = false
    Hovered = FlashSideUI.IsMouseInBounds(CurrentMenu.X + CurrentMenu.SafeZoneSize.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SafeZoneSize.Y + CurrentMenu.SubtitleHeight + FlashSideUI.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height)
    if Hovered and not Selected then
        RenderRectangle(CurrentMenu.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SubtitleHeight + FlashSideUI.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height, 255, 255, 255, 20)
        if CurrentMenu.Controls.Click.Active then
            CurrentMenu.Index = Option
            local Audio = FlashSideUI.Settings.Audio
            FlashSideUI.PlaySound(Audio[Audio.Use].Error.audioName, Audio[Audio.Use].Error.audioRef)
        end
    end
    return Hovered;
end

---ItemsSafeZone
---@param CurrentMenu table
---@return nil
---@public
function FlashSideUI.ItemsSafeZone(CurrentMenu)
    if not CurrentMenu.SafeZoneSize then
        CurrentMenu.SafeZoneSize = { X = 0, Y = 0 }
        if CurrentMenu.Safezone then
            CurrentMenu.SafeZoneSize = FlashSideUI.GetSafeZoneBounds()
            SetScriptGfxAlign(76, 84)
            SetScriptGfxAlignParams(0, 0, 0, 0)
        end
    end
end

function FlashSideUI.CurrentIsEqualTo(Current, To, Style, DefaultStyle)
    if (Current == To) then
        return Style;
    else
        return DefaultStyle or {};
    end
end

function FlashSideUI.RefreshPagination()
    if (FlashSideUI.CurrentMenu ~= nil) then
        if (FlashSideUI.CurrentMenu.Index > 10) then
            local offset = FlashSideUI.CurrentMenu.Index - 10
            FlashSideUI.CurrentMenu.Pagination.Minimum = 1 + offset
            FlashSideUI.CurrentMenu.Pagination.Maximum = 10 + offset
        else
            FlashSideUI.CurrentMenu.Pagination.Minimum = 1
            FlashSideUI.CurrentMenu.Pagination.Maximum = 10
        end
    end
end

function FlashSideUI.IsVisible(menu, header, glare, instructional, items, panels)
    if (FlashSideUI.Visible(menu)) then
        if (header == true) then
            FlashSideUI.Banner(true, glare or false)
        end
        FlashSideUI.Subtitle()
        if (items ~= nil) then
            items()
        end
        FlashSideUI.Background();
        FlashSideUI.Navigation();
        FlashSideUI.Description();
        if (panels ~= nil) then
            panels()
        end
        FlashSideUI.Render(instructional or false)
    end
end


---CreateWhile
---@param wait number
---@param menu table
---@param key number
---@param closure function
---@return void
---@public
function FlashSideUI.CreateWhile(wait, menu, key, closure)
    Citizen.CreateThread(function()
        while (true) do
            Citizen.Wait(wait or 0.1)

            if (key ~= nil) then
                if IsControlJustPressed(1, key) then
                    FlashSideUI.Visible(menu, not FlashSideUI.Visible(menu))
                end
            end

            closure()
        end
    end)
end

---SetStyleAudio
---@param StyleAudio string
---@return void
---@public
function FlashSideUI.SetStyleAudio(StyleAudio)
    FlashSideUI.Settings.Audio.Use = StyleAudio or "FlashSideUI"
end

function FlashSideUI.GetStyleAudio()
    return FlashSideUI.Settings.Audio.Use or "FlashSideUI"
end

